import { Octokit } from '@octokit/rest';
import simpleGit from 'simple-git';
import fs from 'fs';
import path from 'path';
import 'dotenv/config';

// Load config
const repos = JSON.parse(fs.readFileSync('./repos.json', 'utf8'));
const modelMap = JSON.parse(fs.readFileSync('./model-deprecation-map.json', 'utf8'));

// Initialize GitHub API client
const octokit = new Octokit({
  auth: process.env.GITHUB_TOKEN
});

// Setup workspace
const WORKSPACE_DIR = path.resolve('./workspace');

async function main() {
  if (!process.env.GITHUB_TOKEN) {
    console.error("❌ GITHUB_TOKEN environment variable is missing.");
    process.exit(1);
  }

  // Create workspace dir if it doesn't exist
  if (!fs.existsSync(WORKSPACE_DIR)) {
    fs.mkdirSync(WORKSPACE_DIR);
  }

  for (const repo of repos) {
    console.log(`\n🔍 Processing repository: ${repo}...`);
    try {
      await processRepo(repo);
    } catch (error) {
      console.error(`❌ Error processing ${repo}:`, error);
    }
  }
  console.log(`\n✅ All repositories processed.`);
}

async function processRepo(repoFullName) {
  const [owner, repoName] = repoFullName.split('/');
  const repoDir = path.join(WORKSPACE_DIR, repoName);
  
  // Clean up existing directory if any
  if (fs.existsSync(repoDir)) {
    fs.rmSync(repoDir, { recursive: true, force: true });
  }

  const repoUrl = `https://${process.env.GITHUB_TOKEN}@github.com/${repoFullName}.git`;
  
  console.log(`   Clone ${repoFullName}...`);
  const git = simpleGit();
  await git.clone(repoUrl, repoDir);
  
  const repoGit = simpleGit(repoDir);
  const branchName = `chore/update-deprecated-ai-models-${Date.now()}`;
  
  await repoGit.checkoutLocalBranch(branchName);

  console.log(`   Scanning for deprecated models...`);
  const changesMade = scanAndReplace(repoDir);

  if (!changesMade) {
    console.log(`   No deprecated models found in ${repoFullName}.`);
    return;
  }

  console.log(`   Changes detected! Committing and pushing...`);
  
  // Set up git user
  await repoGit.addConfig('user.name', 'AI Model Updater Bot');
  await repoGit.addConfig('user.email', 'updater-bot@users.noreply.github.com');

  await repoGit.add('./*');
  await repoGit.commit('chore: update deprecated AI models');
  
  // Push the branch
  await repoGit.push('origin', branchName);

  console.log(`   Opening Pull Request...`);
  await octokit.pulls.create({
    owner,
    repo: repoName,
    title: 'Update Deprecated AI Models',
    head: branchName,
    base: 'main', // Make sure the repo uses 'main' as default branch, otherwise change this or fetch dynamically
    body: `This PR automatically updates deprecated AI models to their modern equivalents based on the model deprecation map.
    
*This is an automated PR generated by the AI Model Updater Bot.*`
  });

  console.log(`   🎉 Pull Request created successfully!`);
}

function scanAndReplace(dir) {
  let hasChanges = false;
  const files = fs.readdirSync(dir);

  for (const file of files) {
    const fullPath = path.join(dir, file);
    
    // Ignore common non-code directories
    if (fs.statSync(fullPath).isDirectory()) {
      if (['node_modules', '.git', 'dist', 'build', '.next'].includes(file)) continue;
      if (scanAndReplace(fullPath)) hasChanges = true;
    } else {
      // Basic text file check (skip binary files if possible, here we just read as utf8)
      try {
        let content = fs.readFileSync(fullPath, 'utf8');
        let originalContent = content;
        
        // Iterate over the deprecation map
        for (const [deprecatedModel, info] of Object.entries(modelMap)) {
          // Regex to match the deprecated model name
          const regex = new RegExp(`(?<![a-zA-Z0-9_-])(${deprecatedModel})(?![a-zA-Z0-9_-])`, 'g');
          if (regex.test(content)) {
            console.log(`     Found ${deprecatedModel} in ${file}, replacing with ${info.replacement}`);
            content = content.replace(regex, info.replacement);
          }
        }

        if (content !== originalContent) {
          fs.writeFileSync(fullPath, content, 'utf8');
          hasChanges = true;
        }
      } catch (err) {
        // Handle read errors (e.g. binary files)
        console.error(`     Error reading ${file}: ${err.message}`);
      }
    }
  }

  return hasChanges;
}

main();
